### ISSUE TITLE
Adaptation of the algorithm for rectangular robots

### ISSUE THREAD

**Issue by astef3** [nachoh8/NearnessDiagram-ROS#1]
Hi,

I work on a project that involves robot of a rectangular shape, that is driven by four omni-directional wheels. The project is mainly dedicated to autonomous navigation with ROS, and when I did the research about available local planners, it seemed to me that the ND algorithm shows extremely good results. Because of that, I decided to try and implement it in my project. However, in all sources I have found so far it says that the algorithm was primarily developed for circular robots, but it is possible to adapt the algorithm in order to fit the specifications of the robot. Also in your report, you mentioned that your code is developed for circular robots, but it can be adapted.

So I hoped if someone can give me some advice on how to adapt the code in order to make the application work. Also, I tried a simple solution(not optimal), to approximate my robot as a circular robot with radius that is half of the diagonal of the robot, so I can cover the whole surface of the robot. However, when I test it , when I set the goal, the robot moves to the goal, reaches it or nearly reaches it and then it starts to rotate in place with the maximum rotational velocity I set in the yaml file and it does not stop. Do you maybe have some advice on what might cause this issue and how to fix it? 

Also I would like to mention that you did and outstanding job with transforming the paper from the developers to a functional code.

I would really appreciate to hear your opinions and also thank you for your time.

**Comment by nachoh8** [comment]
Hi, to adapt the planner for rectangular robots you have to
first, create a function _E(i)_ that gives you the distance from the center of the robot to the robot surface on sector _i_ and you have to use this function on computing RND
second, when computing PND you have to calculate the maximun distance between two points on the robot surface (_l_ in the report and _robot_fit_ in the code).

I don't know if I've left anything out, but it's a good point to start.

**Comment by astef3** [comment]
Thank you so much! I will start working on the adaptions and will let you know how it goes.

**Comment by astef3** [comment]
HI, 

I adapted everything as you mentioned, but I still have the same problem as previously mentioned. When the robot reaches the set goal, it starts rotating with constant rotational velocity(the velocity is equal to the value I set in the yaml file). Based on the behaviour it seems like it is some recovery behaviour which is set in move base, but I also tried setting those parameters to False, but the result is the same. Have you maybe experienced something like this before or if you have any idea what might be causing this issue, so you can advise me what to change or try as a possible fix of the problem? Thanks you in advance.

Also, I did not quite understand the parameter ls2_diff, can you please tell me what does it represent and how does it influence the algorithm?

**Comment by nachoh8** [comment]
It is possible that there is a bug, because we didn't have much time to test it, but we never had the problem of robot not stopping rotating when it reached the goal. But you can force the rotation speed to be 0 when the goal is reached.
The parameter  _ls2_diff_ appears as _D_ in the report in the case of Low Safety 2 (LS2). It acts as the maximum number of sectors to move away from the center between the two obstacles, as the robot is closer to one obstacle than the other it will move further away. Although it does not greatly affect the final performance.

**Comment by astef3** [comment]
Hi, I solved the problem. When I started debugging, I understood that actually the condition in the isGoalReached() function was not being set, so I fixed that problem and now everything is okay. Thank you so much for the help.
